name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  macos:
    strategy:
      matrix:
        xcode:
          - "14.3.1"

    name: macOS 13 (Xcode ${{ matrix.xcode }})
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: make test-swift

  ubuntu:
    strategy:
      matrix:
        swift:
          - "5.7"

    name: Ubuntu (Swift ${{ matrix.swift }})
    runs-on: ubuntu-20.04
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - run: swift test

  wasm:
    name: SwiftWasm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - wasm-5.9.2-RELEASE
          - wasm-5.10.0-RELEASE 
    steps:
      - name: Cache toolchains
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Toolchains
          key: ${{ matrix.toolchain }}
      - uses: actions/checkout@v4
      - uses: bytecodealliance/actions/wasmtime/setup@v1
      - uses: swiftwasm/setup-swiftwasm@v1
        with:
          swift-version: ${{ matrix.toolchain }}
      - name: Build tests
        run: swift build --triple wasm32-unknown-wasi --build-tests -Xlinker -z -Xlinker stack-size=$((1024 * 1024))
      - name: Run tests
        run: wasmtime .build/debug/swift-snapshot-testingPackageTests.wasm

  windows:
    strategy:
      matrix:
        swift:
          - "5.9.1"

    name: Windows (Swift ${{ matrix.swift }})
    runs-on: windows-latest

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-${{ matrix.swift }}-release
          tag: ${{ matrix.swift }}-RELEASE

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4
      - run: swift build
      - run: swift test
