name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  macos:
    strategy:
      matrix:
        xcode:
          - '16.2'

    name: macOS
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: make test-swift

  ubuntu:
    strategy:
      matrix:
        swift:
          - '6.1'

    container: swift:${{ matrix.swift }}
    name: Linux (Swift ${{ matrix.swift }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: swift test

  # windows:
  #   strategy:
  #     matrix:
  #       swift:
  #         - "6.1"

  #   name: Windows (Swift ${{ matrix.swift }})
  #   runs-on: windows-latest

  #   steps:
  #     - uses: compnerd/gha-setup-swift@main
  #       with:
  #         branch: swift-${{ matrix.swift }}-release
  #         tag: ${{ matrix.swift }}-RELEASE

  #     - name: Set git to use LF
  #       run: |
  #         git config --global core.autocrlf false
  #         git config --global core.eol lf

  #     - uses: actions/checkout@v4
  #     - run: swift build
  #     - run: swift test

  android:
    strategy:
      matrix:
        swift:
          - "6.0.2"
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: skiptools/swift-android-action@v2
        with:
          swift-version: ${{ matrix.swift }}
          copy-files: ${GITHUB_WORKSPACE}/Tests/SnapshotTestingTests/__Snapshots__
